import dbService from '../../service/dbService'
import animal from '../../service/dbService/sf_animal'
import { ErrorHandle } from '../../common/errorHandle'
import moment from 'moment'
import { Model, FindOptions, FindAttributeOptions, UpdateOptions } from 'sequelize/types'
import sequelize from 'sequelize'
